version: '3'

services:
  pet-hope-pg:

    image: bitnami/postgresql
    container_name: pet-hope-pg
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pethope